### ISSUE TITLE
Implement proper error if oAuth v2 reidrect URI is invalid

### ISSUE THREAD

**Issue by kimar** [LocativeHQ/cloud-app#26]
Currently this shows a plain 500 mode (production) or stacktrace (dev)

```
[locative-1 (err)]  does not match!
[locative-1 (err)]     at Promise.<anonymous> (/home/geofancy/locative/lib/oauth2.js:166:21)
[locative-1 (err)]     at Promise.<anonymous> (/home/geofancy/locative/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
[locative-1 (err)]     at Promise.emit (events.js:95:17)
[locative-1 (err)]     at Promise.emit (/home/geofancy/locative/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
[locative-1 (err)]     at Promise.fulfill (/home/geofancy/locative/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
[locative-1 (err)]     at /home/geofancy/locative/node_modules/mongoose/lib/query.js:1406:13
[locative-1 (err)]     at model.Document.init (/home/geofancy/locative/node_modules/mongoose/lib/document.js:254:11)
[locative-1 (err)]     at completeOne (/home/geofancy/locative/node_modules/mongoose/lib/query.js:1404:10)
[locative-1 (err)]     at Object.cb (/home/geofancy/locative/node_modules/mongoose/lib/query.js:1158:11)
[locative-1 (err)]     at Object._onImmediate (/home/geofancy/locative/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
[locative-1 (err)]     at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by kimar** [comment]
Has been fixed together with https://github.com/LocativeHQ/cloud-app/commit/8bb17a036a420ba5224c6cdb6d47bd67cebf0633
